### ISSUE TITLE
Pure Javascript implementation?

### ISSUE THREAD

**Issue by maeishoj** [26medias/timeseries-analysis#1]
Is it possible to use this in front end? Are you aware of any similar library?

**Comment by 26medias** [comment]
Hi,

Yes, you can use front-end, but you'll have to make a few changes to timeseries-analysis.js

First, load underscore.js on your page (http://underscorejs.org/)
Then, remove the "require(...)" on top of the file and remove the "exports.*" at the bottom.

Then use as per the doc.
If you wish to use the chart() method, you'll have to also modify the "google-image-chart" dependency to make it work on the client-side but it might be faster to just re-implement a new charting function using something like highcharts for example.

I haven't used that client-side, and I'm not sure if there are other libs that do that type of thing.

**Comment by maeishoj** [comment]
Hey there! Thanks a lot!!
