### ISSUE TITLE
coeffs NaN

### ISSUE THREAD

**Issue by maeishoj** [26medias/timeseries-analysis#2]
Hey there.

I am successfully running this to do some forecast on some data samples i periodically store.

However I just tried to do the same code that works on larger dataset (60+ datapoints) on a small dataset (8 datapoints) and the coeffs that I calculate like so:

var coeffs = t.ARMaxEntropy({
                data: t.data
            });

contains [NaN, NaN, NaN, NaN, NaN]

Why is that? is it because I use 5 coeffs and my dataset is too small?

**Comment by 26medias** [comment]
Hi,

Your dataset is too small.

**Comment by roblav96** [comment]
I've noticed that anything lower than 10 points will result in this error.

Absolutely astounding work here!

**Comment by 26medias** [comment]
Thanks :)

**Comment by amprodes** [comment]
HI! in this line of code "t.smoother({period:4}).save('smoothed'" what does mean {period:4} ?

**Comment by muazhari** [comment]
hi @maeishoj, can I get your code to forecast new n values?
